  
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const POST_USERS_SUCCESS  = 'POST_USERS_SUCCESS'
export const POST_USERS_FAILURE  = 'POST_USERS_FAILURE'